update the results checks done
Now beta and edge validation have same behaviour

diff --git a/validation/job-executor b/validation/job-executor
--- a/validation/job-executor
+++ b/validation/job-executor
@@ -37,26 +37,19 @@ echo "Analyzing results and exis status"
 # In case there are successful tasks it means the execution finished and there is at least 1 test executed successfully
 if grep -e "Successful tasks:" "$SPREAD_LOG"; then
     # For edge cahnnel, a successful run is when all the tests have pass
-    if [ "$CHANNEL" = edge ]; then
-        if grep -E "Failed (task|suite|project)" "$SPREAD_LOG" && ! grep -e "Aborted tasks: 0" "$SPREAD_LOG"; then
-            echo "Execution finished and either not spread results included in log or there are failed/aborted tests in the logs"
-            EXIT_STATUS=1
-        else
-            echo "Execution finished and spread results included in log without failed/aborted tests"
-            EXIT_STATUS=0
-        fi
-    # For beta, candidate or stable, a successful run is when the execution finished without aborted tests
-    # This is because there are known issues which fail and logs require manual review. In case of all tests
-    # passed, the the jira card is automatically set as passed for that run.
-    else
-        if ! grep -e "Aborted tasks: 0" "$SPREAD_LOG"; then
-            echo "Execution finished and either not spread results included in log or there are aborted tests in the log"
-            EXIT_STATUS=1
-        else
-            echo "Execution finished and spread results included in log without aborted tests"
-            EXIT_STATUS=0
-        fi
+    EXIT_STATUS=0
+    if grep -E "Failed (task|suite|project)" "$SPREAD_LOG"; then
+        echo "Execution finished with failed tests"
+        EXIT_STATUS=1
     fi
+    if ! grep -e "Aborted tasks: 0" "$SPREAD_LOG"; then
+        echo "Execution finished with aborted tests"
+        EXIT_STATUS=1
+    fi
+
+    if [ "$EXIT_STATUS" = "0" ]; then
+        echo "Execution finished without failed/aborted tests"
+    fi    
 else
     echo "Execution didn't finish and/or no tests passing in spread log"
     EXIT_STATUS=1
