Update indentation

diff --git a/validation/services/job-executor b/validation/services/job-executor
--- a/validation/services/job-executor
+++ b/validation/services/job-executor
@@ -10,15 +10,15 @@ TESTS_CONFIG=$5
 WORKSPACE=$6
 
 if [ ! "$PROJECT" ]; then
-	echo "Porject not defined, exiting..."
-	exit 1
+    echo "Porject not defined, exiting..."
+    exit 1
 fi
 
 # Load environment variables
 . "${WORKSPACE}/snapd-testing/validation/services/env/common.sh" "$WORKSPACE"
 if [ ! -f "${WORKSPACE}/snapd-testing/validation/services/env/${SERVICE_ENV}.sh" ]; then
-	echo "configuration file does not exist, exiting"
-	exit 1
+    echo "configuration file does not exist, exiting"
+    exit 1
 fi
 . "${WORKSPACE}/snapd-testing/validation/services/env/${SERVICE_ENV}.sh"
 
@@ -30,8 +30,8 @@ export $TESTS_ENV
 
 # Prepare tests environment
 if [ "$PROJECT" == snapd ]; then
-	VERSION="$(${WORKSPACE}/snapd-testing/snap-version.sh $SNAP_UT $TARGET_CHANNEL amd64)"
-	export BRANCH="$(${WORKSPACE}/snapd-testing/scripts/git-branch.sh $VERSION)"
+    VERSION="$(${WORKSPACE}/snapd-testing/snap-version.sh $SNAP_UT $TARGET_CHANNEL amd64)"
+    export BRANCH="$(${WORKSPACE}/snapd-testing/scripts/git-branch.sh $VERSION)"
 fi
 
 # Run spread tests
@@ -40,43 +40,43 @@ fi
 # Determining the exit status for the run
 # For edge cahnnel, a successful run is when all the tests have pass
 if [ "$TARGET_CHANNEL" = edge ]; then
-	if grep -e "Successful tasks:" "$SPREAD_LOG" && ! grep -e "Aborted tasks:" "$SPREAD_LOG" && ! grep -e "Failed tasks:" "$SPREAD_LOG"; then
-    	echo "Execution finished and spread results included in log without failed/aborted tests"
-    	EXIT_STATUS=0
+    if grep -e "Successful tasks:" "$SPREAD_LOG" && ! grep -e "Aborted tasks:" "$SPREAD_LOG" && ! grep -e "Failed tasks:" "$SPREAD_LOG"; then
+        echo "Execution finished and spread results included in log without failed/aborted tests"
+        EXIT_STATUS=0
     else
-    	echo "Execution finished and either not spread results included in log or there are failed/aborted tests in the logs"
-    	EXIT_STATUS=1
+        echo "Execution finished and either not spread results included in log or there are failed/aborted tests in the logs"
+        EXIT_STATUS=1
     fi
 # For beta, candidate or stable, a successful run is when the execution finished without aborted tests
 # This is because there are known issues which fail and logs require manual review. In case of all tests
 # passed, the the trello/jira card is automatically set as passed for that run.
 else
-	if grep -e "Successful tasks:" -e "Failed tasks:" "$SPREAD_LOG" && ! grep -e "Aborted tasks:" "$SPREAD_LOG"; then
-	    echo "Execution finished and spread results included in log without aborted tests"
-	    EXIT_STATUS=0
-	else
-	    echo "Execution finished and either not spread results included in log or there are aborted tests in the log"
-	    EXIT_STATUS=1
-	fi
+    if grep -e "Successful tasks:" -e "Failed tasks:" "$SPREAD_LOG" && ! grep -e "Aborted tasks:" "$SPREAD_LOG"; then
+        echo "Execution finished and spread results included in log without aborted tests"
+        EXIT_STATUS=0
+    else
+        echo "Execution finished and either not spread results included in log or there are aborted tests in the log"
+        EXIT_STATUS=1
+    fi
 fi
 
 if [ -z "$IMAGE_UT" ]; then
-	# Get version and revision for snap under test
-	OBJECT_UT="$SNAP_UT"
-	VERSION_UT="$(${WORKSPACE}/snapd-testing/scripts/snap-version.sh $SNAP_UT $TARGET_CHANNEL amd64)"
-	REVISION_UT="$(${WORKSPACE}/snapd-testing/scripts/snap-revision.sh $SNAP_UT $TARGET_CHANNEL amd64)"
+    # Get version and revision for snap under test
+    OBJECT_UT="$SNAP_UT"
+    VERSION_UT="$(${WORKSPACE}/snapd-testing/scripts/snap-version.sh $SNAP_UT $TARGET_CHANNEL amd64)"
+    REVISION_UT="$(${WORKSPACE}/snapd-testing/scripts/snap-revision.sh $SNAP_UT $TARGET_CHANNEL amd64)"
 else
-	OBJECT_UT="$IMAGE_UT"
-	VERSION_UT="$TARGET_CHANNEL"
-	REVISION_UT="($(date +%Y%m%d))"
+    OBJECT_UT="$IMAGE_UT"
+    VERSION_UT="$TARGET_CHANNEL"
+    REVISION_UT="($(date +%Y%m%d))"
 fi
 
 # Integrate results with trello board
 "${WORKSPACE}/snapd-testing/validation/services/trello-integrator" "$OBJECT_UT" "$VERSION_UT" "$REVISION_UT" "$TARGET_CHANNEL" "$TRELLO_CONFIG" "$BOARD_UT" "$ARCH_UT" "$SPREAD_LOG" "$SUMMARY_LOG" "$ATTACH_LOG"
 if [ -n "$JIRA_ACCESS_TOKEN" ] && [ -n "$JIRA_ACCESS_TOKEN_SECRET" ] && [ -n "$JIRA_KEY_CERT" ]; then
-	"${WORKSPACE}/snapd-testing/validation/services/jira-integrator" "$OBJECT_UT" "$VERSION_UT" "$REVISION_UT" "$TARGET_CHANNEL" "$TRELLO_CONFIG" "$BOARD_UT" "$ARCH_UT" "$SPREAD_LOG" "$SUMMARY_LOG" "$ATTACH_LOG"
+    "${WORKSPACE}/snapd-testing/validation/services/jira-integrator" "$OBJECT_UT" "$VERSION_UT" "$REVISION_UT" "$TARGET_CHANNEL" "$TRELLO_CONFIG" "$BOARD_UT" "$ARCH_UT" "$SPREAD_LOG" "$SUMMARY_LOG" "$ATTACH_LOG"
 else
-	echo "Skipping jira integration, variables needed in the environment: JIRA_ACCESS_TOKEN, JIRA_ACCESS_TOKEN_SECRET and JIRA_KEY_CERT"
+    echo "Skipping jira integration, variables needed in the environment: JIRA_ACCESS_TOKEN, JIRA_ACCESS_TOKEN_SECRET and JIRA_KEY_CERT"
 fi
 
 exit "$EXIT_STATUS"
